routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/register', function () {
    abort(404);
});
Route::post('/register', function () {
    abort(401);
});

Route::get('/', 'App\Http\Controllers\TshirtController@create');
Route::resource('/t-shirts', 'App\Http\Controllers\TshirtController');
Route::post('/t-shirts/check/name/availability', 'App\Http\Controllers\TshirtController@checkNameAvailability')->name('t-shirts.check.name.availability');

app/Models/Tshirt.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Tshirt extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'created_by', 'updated_by'];

    public function rawMaterials()
    {
        return $this->hasMany(TshirtRawMaterial::class);
    }


    public function totalPrice()
    {
        $total_price = 0;

        foreach ($this->rawMaterials as $trm) {
            $total_price += $trm->rawMaterial->price * $trm->qty;
        }
        return $total_price;
    }

    public function givenQty($raw_material_id)
    {
        $qty = 0;
        $data = TshirtRawMaterial::select(['qty'])
            ->where(['tshirt_id' => $this->id, 'raw_material_id' => $raw_material_id])
            ->first();

        if ($data) {
            $qty = $data->qty;
        }
        return $qty;

    }
}

app/Http/Controllers/TshirtController.php
<?php

namespace App\Http\Controllers;

use App\Models\RawMaterial;
use App\Models\Tshirt;
use App\Models\TshirtRawMaterial;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TshirtController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Tshirt::orderBy('created_at', 'DESC')->get(['id', 'name']);
        return view('t-shirt.browse', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $raw_materials = RawMaterial::get();
        return view('t-shirt.add-edit', compact('raw_materials'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            $rules = [
                'name' => 'required|unique:tshirts',
                'raw_materials_qty.*' => 'required|numeric',
            ];

            $data = $request->except(['_token']);


            $validator = Validator::make($data, $rules);

            if ($validator->fails()) {

                return response()->json([
                    'status' => 'error',
                    'message' => $validator->messages()
                ]);
            }

            $data['created_by'] = auth()->user()->id;
            $tshirt = Tshirt::create($data);

            if ($tshirt) {
                $inputrawMaterialData = $request->except(['_token', 'name']);
                $rawMaterialData = [];

                foreach ($inputrawMaterialData['raw_materials_qty'] as $k => $qty) {

                    $is_rm_in_db = RawMaterial::where('id', $k)->count();

                    if ($is_rm_in_db > 0) {
                        $rawMaterialData [] = [
                            'tshirt_id' => $tshirt->id,
                            'raw_material_id' => $k,
                            'qty' => $qty,
                            'created_by' => auth()->user()->id
                        ];
                    }
                }

                if (TshirtRawMaterial::insert($rawMaterialData)) {

                    return response()->json([
                        'status' => 'success',
                        'message' => 'New T-shirt Crated Successfully.'
                    ]);
                }

            }

            return response()->json([
                'status' => 'success',
                'message' => 'Something went wrong!'
            ]);


        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Tshirt $tshirtController
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Tshirt::findorfail($id);
        $raw_materials = RawMaterial::get();
        return view('t-shirt.view', compact('model','raw_materials'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Tshirt $model
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Tshirt::findorfail($id);
        $raw_materials = RawMaterial::get();
        return view('t-shirt.add-edit', compact('raw_materials', 'model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Tshirt $tshirtController
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {

            $rules = [
                'name' => 'required',
                'raw_materials_qty.*' => 'required|numeric',
            ];

            $data = $request->except(['_token']);


            $validator = Validator::make($data, $rules);

            if ($validator->fails()) {

                return response()->json([
                    'status' => 'error',
                    'message' => $validator->messages()
                ]);
            }


            $tshirt = Tshirt::findorfail($id);

            if ($tshirt) {
                $data['updated_by'] = auth()->user()->id;
                $tshirt->update($data);


                $inputrawMaterialData = $request->except(['_token', 'name']);
                $rawMaterialData = [];

                foreach ($inputrawMaterialData['raw_materials_qty'] as $k => $qty) {

                    $is_rm_in_db = RawMaterial::where('id', $k)->count();

                    if ($is_rm_in_db > 0) {
                        $rawMaterialData [] = [
                            'tshirt_id' => $tshirt->id,
                            'raw_material_id' => $k,
                            'qty' => $qty,
                            'updated_by' => auth()->user()->id
                        ];
                    }
                }

                if (TshirtRawMaterial::where('tshirt_id', $tshirt->id)->delete() && TshirtRawMaterial::insert($rawMaterialData)) {

                    return response()->json([
                        'status' => 'success',
                        'message' => 'T-shirt Updated Successfully.'
                    ]);
                }

            }

            return response()->json([
                'status' => 'success',
                'message' => 'Something went wrong!'
            ]);


        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Tshirt $tshirtController
     * @return \Illuminate\Http\Response
     */
    public function destroy(TshirtController $tshirtController)
    {
        //
    }

    public function checkNameAvailability(Request $request)
    {
        try {
            $is_available = Tshirt::where('name', $request->name)->where('id', '<>', $request->model_id)->count();

            if ($is_available > 0) {
                return response()->json(false);
            }
            return response()->json(true);
        } catch (\Exception $e) {
            return response()->json([
                'status' => 'error',
                'message' => $e->getMessage()
            ]);
        }

    }

}

resources/views/t-shirt/add-edit.blade.php
@extends('layouts.admin.app')
@section('css')
    <style>
        .table td, .table th {
            padding: 8px;
        }

        .form-control {
            height: 40px;
        }
    </style>
@endsection
@section('content')

    <section class="pcoded-main-container">


        <div class="modal-dialog modal-xl" role="document">
            <form
                action="@if(isset($model) && $model) {{route('t-shirts.update',$model)}} @else {{route('t-shirts.store')}} @endif"
                id="add-edit-form" method="POST">
                @csrf
                @if(isset($model) && $model)
                    @method('patch')
                @endif


                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLiveLabel">
                            @if(isset($model) && $model) Edit @else Create New @endif T-shirt
                        </h5>

                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for=""><span class="text-danger">*</span>T-shirt Name :</label>
                                    <input type="text" class="form-control mandatory" name="name"
                                           value="{{ isset($model) ? $model->name : ''}}"
                                           placeholder="Enter T-shirt name">
                                    <span class="error_title error"></span>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label>Total Price:</label>
                                <span class="form-control text-success"
                                      id="total_price">{{ isset($model) ? $model->totalPrice() : ''}}</span>

                            </div>

                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <h5>Raw Materials</h5>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Unit</th>
                                        <th>Price</th>
                                        <th width="15%">Qty</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($raw_materials as $k => $data)
                                        <tr>
                                            <td>
                                                <img height="30px;" src="{{url('/')}}/{{$data->icon}}"/>
                                                {{$data->name}}
                                            </td>
                                            <td>{{$data->unit}}</td>
                                            <td>{{$data->price}}</td>
                                            <td>
                                                <input class="form-control  digit" type="tel"
                                                       name="raw_materials_qty[{{$data->id}}]"
                                                       data-price="{{$data->price}}"
                                                       value="{{isset($model) && $model ? $model->givenQty($data->id) : 0}}">
                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                    <tfoot>
                                    <tr>
                                    </tr>
                                    </tfoot>
                                </table>

                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="final_submit" class="btn btn-sm btn-primary"><i class="feather icon-save"></i>
                            @if(isset($model) && $model) Update @else Save @endif
                        </button>
                    </div>
                </div>
            </form>
        </div>


    </section>



@endsection

@section('javascript')
    <script src="{{asset('backend_resources/js/jquery_validation_combine.js')}}"></script>
    <script>
        var totalPrice = 0;
        var is_edit = '{{isset($model) && $model ? 1: 0}}';

        function loaderToggle(t) {
            if (t == 1) {
                $('.loader-bg').fadeIn('slow')
            } else {
                $('.loader-bg').fadeOut('fast')
            }
        }


        $("#add-edit-form").validate({
            rules: {
                name: {
                    required: true,
                    remote: {
                        url: "{{route('t-shirts.check.name.availability')}}",
                        type: 'POST',
                        data: {model_id: '{{ isset($model) && $model ? $model->id: 0 }}'},
                        delay: 500,
                    }
                },


            },
            messages: {
                name: {
                    remote: "This name has already been taken!"
                }
            },

            submitHandler: function (form, e) {
                loaderToggle(1)
                save()
            }
        });


        function save() {

            $.ajax({
                url: $('#add-edit-form').attr('action'),
                type: $('#add-edit-form').attr('method'),
                cache: false,
                data: $('#add-edit-form').serialize(),
                success: function (response) {
                    loaderToggle(0)
                    $('.error_title').empty();
                    $('.error_price').empty();
                    if (response.status == 'success') {
                        toastr.success(response.message);

                        if (is_edit == 0) {
                            $('input').val('')
                            setTotalPrice()
                        }

                    } else {
                        toastr.error(response.message);
                    }
                },
                error: function (response) {
                    loaderToggle(0)
                    console.log(response)
                }

            });

        }

        $('.mandatory').each(function () {
            $(this).rules("add", {
                required: true,
                messages: {
                    required: "This field is required.",
                },
            });
        });

        $('.digit').each(function () {
            $(this).rules("add", {
                digits: true,
                required: true,
                minlength: 1

            });
        });

        $('.digit').on('input', function () {
            setTotalPrice()
        });


        function setTotalPrice() {
            totalPrice = 0;
            $('.digit').each(function () {
                totalPrice += parseInt($(this).data('price')) * parseInt(this.value)
            });
            $('#total_price').html(totalPrice)
        }

        $('[type=tel]').on('change', function (e) {
            $(e.target).val($(e.target).val().replace(/[^\d]/g, ''))
        })
        $('[type=tel]').on('keypress', function (e) {
            keys = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
            return keys.indexOf(event.key) > -1
        })


    </script>

@endsection

resources/views/t-shirt/browse.blade.php
@extends('layouts.admin.app')

@section('title')

@endsection

@section('css')
    <style>
        .table > :not(:first-child) {
            border-top: 0;
        }
    </style>
@endsection

@section('content')
    <section class="pcoded-main-container">
        <div class="pcoded-content">
            <!-- [ breadcrumb ] start -->
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="portlet-title">
                                <div class="tools pull-right">
                                    <div class="m-3">
                                        <b>T-shirt List</b>
                                    </div>
                                    <button onclick="newTshirt()" type="button" class="btn btn-sm btn-success"
                                            data-toggle="modal" data-target="#addPackage"><i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                            <hr class="m-0">
                            <div class="card-body">
                                <table id="dataTable" class="table table-striped table-sm table-hover text-center">
                                    <thead class="text-center">
                                    <tr class="text-center">
                                        <th>Sl</th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>

                                    <tbody id="packagesBody">

                                    @foreach($data as $k => $d)
                                        <tr>
                                            <td>{{$k+1}}</td>
                                            <td>{{$d->name}}</td>
                                            <td>{{$d->totalPrice()}}</td>
                                            <td>
                                                <a class="btn btn-secondary"
                                                   href="{{route('t-shirts.edit',$d)}}">Edit</a>
                                                <a class="btn btn-info" href="{{route('t-shirts.show',$d)}}">View</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



@endsection

@section('javascript')

    <script>

        function newTshirt() {
            location = "{{route('t-shirts.create')}}"
        }
    </script>

@endsection

resources/views/t-shirt/view.blade.php
@extends('layouts.admin.app')
@section('css')
    <style>
        .table td, .table th {
            padding: 8px;
        }

        .form-control {
            height: 40px;
        }
    </style>
@endsection
@section('content')

    <section class="pcoded-main-container">


        <div class="modal-dialog modal-xl" role="document">


            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLiveLabel">
                       View T-shirt
                    </h5>

                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for=""><span class="text-danger"></span>T-shirt Name :</label>
                                <input type="text" class="form-control mandatory" name="name"
                                       value="{{ isset($model) ? $model->name : ''}}"
                                       placeholder="Enter T-shirt name">
                                <span class="error_title error"></span>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <label>Total Price:</label>
                            <span class="form-control text-success"
                                  id="total_price">{{ isset($model) ? $model->totalPrice() : ''}}</span>

                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <h5>Raw Materials</h5>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Unit</th>
                                    <th>Price</th>
                                    <th width="15%">Qty</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($raw_materials as $k => $data)
                                    <tr>
                                        <td>
                                            <img height="30px;" src="{{url('/')}}/{{$data->icon}}"/>
                                            {{$data->name}}
                                        </td>
                                        <td>{{$data->unit}}</td>
                                        <td>{{$data->price}}</td>
                                        <td>
                                            <input class="form-control  digit" type="tel"
                                                   name="raw_materials_qty[{{$data->id}}]"
                                                   data-price="{{$data->price}}"
                                                   value="{{isset($model) && $model ? $model->givenQty($data->id) : 0}}">
                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                                <tfoot>
                                <tr>
                                </tr>
                                </tfoot>
                            </table>

                        </div>
                    </div>
                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div>


    </section>


@endsection

@section('javascript')
    <script>
        $('input').attr('readonly',true)
    </script>

@endsection