routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/register', function () {
    abort(404);
});
Route::post('/register', function () {
    abort(401);
});

Route::get('/', 'App\Http\Controllers\TshirtController@create');
Route::resource('/t-shirts', 'App\Http\Controllers\TshirtController');
Route::post('/t-shirts/check/name/availability', 'App\Http\Controllers\TshirtController@checkNameAvailability')->name('t-shirts.check.name.availability');

resources/views/layouts/admin/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'CMS') }}</title>

    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="icon" href="{{asset('assets/images/favicon.ico')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
    <link rel="stylesheet" href="http://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('backend_resources/css/datatable/datatables.min.css') }}">
    <style>
        div.dataTables_wrapper div.dataTables_filter input {
            width: 175px;
        }

        .pull-right {
            justify-content: space-between;
            display: flex;
            margin: 10px 10px 10px 0px;
        }

        .pull-right button {
            height: 40px;
            width: 40px;
            border-radius: 50%;
        }

        .fixed-button {
            display: none;
        }

        .error {
            color: red !important;
        }

        #itemBody a {
            color: white;
        }

        .btn-success {
            background: #1abc9c !important;
            border: none;
            padding: 8px;
        }

        .table.dataTable {
            width: 100% !important;
        }
    </style>
    @yield('css')
</head>
<body>
<div id="app">
    <div class="loader-bg">
        <div class="loader-track">
            <div class="loader-fill"></div>
        </div>
    </div>
    <!-- Add sidebar and nav bar -->
    @if(auth()->user())
        @include('layouts.admin.sidebar')
        @include('layouts.admin.nav-bar')
    @endif
    @yield('content')
</div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{{asset('assets/js/vendor-all.min.js')}}"></script>
<script src="{{asset('assets/js/plugins/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/pcoded.min.js')}}"></script>
<script src="{{asset('assets/js/plugins/apexcharts.min.js')}}"></script>
<!-- custom-chart js -->
{{--<script src="{{asset('assets/js/pages/dashboard-main.js')}}"></script>--}}
<script src="{{ asset('backend_resources/js/datatable/datatables.min.js') }}"></script>
<script src="http://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js"></script>
@yield('javascript')
<script>
    $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
    // for removing backdrop of a modal
    $('.modal').attr({
        "data-backdrop": "static",
        "data-keyboard": false
    });
</script>

</html>

resources/views/layouts/admin/nav-bar.blade.php
<header class="navbar pcoded-header navbar-expand-lg navbar-light header-dark">
    <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
        <a href="#!" class="b-brand">
            <span style="font-size: 16px"> {{ config('app.name', 'Laravel') }}</span>

        </a>
        <a href="#!" class="mob-toggler">
            <i class="feather icon-more-vertical"></i>
        </a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
        </ul>
        <ul class="navbar-nav ml-auto">

            <li>
                <div class="dropdown drp-user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="feather icon-user"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-notification">
                        <div class="pro-head">

                            <div class="row">
                                <div class="col-md-3">
                                    <img src="{{url('/')}}/{{Auth::user()->avatar}}" class="img-radius" alt="User-Profile-Image">
                                </div>
                                <div class="col-md-9">
                                    <span> {{ Auth::user()->name }}</span>
                                </div>
                            </div>

                        </div>
                        <ul class="pro-body">
                            <li>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    <i class="feather icon-lock"></i> {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>

                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</header>

resources/views/layouts/admin/notification.blade.php
<li>
    <div class="dropdown">
        <a class="dropdown-toggle" href="#" data-toggle="dropdown">
            <i class="icon feather icon-bell"></i>
            <span class="badge badge-pill badge-danger">5</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right notification">
            <div class="noti-head">
                <h6 class="d-inline-block m-b-0">Notifications</h6>
                <div class="float-right">
                    <a href="#!" class="m-r-10">mark as read</a>
                    <a href="#!">clear all</a>
                </div>
            </div>
            <ul class="noti-body">
                <li class="n-title">
                    <p class="m-b-0">NEW</p>
                </li>
                <li class="notification">
                    <div class="media">
                        <img class="img-radius" src="assets/images/user/avatar-1.jpg" alt="Generic placeholder image">
                        <div class="media-body">
                            <p><strong>John Doe</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>5 min</span></p>
                            <p>New ticket Added</p>
                        </div>
                    </div>
                </li>
                <li class="n-title">
                    <p class="m-b-0">EARLIER</p>
                </li>
                <li class="notification">
                    <div class="media">
                        <img class="img-radius" src="assets/images/user/avatar-2.jpg" alt="Generic placeholder image">
                        <div class="media-body">
                            <p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>10 min</span></p>
                            <p>Prchace New Theme and make payment</p>
                        </div>
                    </div>
                </li>
                <li class="notification">
                    <div class="media">
                        <img class="img-radius" src="assets/images/user/avatar-1.jpg" alt="Generic placeholder image">
                        <div class="media-body">
                            <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>12 min</span></p>
                            <p>currently login</p>
                        </div>
                    </div>
                </li>
                <li class="notification">
                    <div class="media">
                        <img class="img-radius" src="assets/images/user/avatar-2.jpg" alt="Generic placeholder image">
                        <div class="media-body">
                            <p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                            <p>Prchace New Theme and make payment</p>
                        </div>
                    </div>
                </li>
            </ul>
            <div class="noti-footer">
                <a href="#!">show all</a>
            </div>
        </div>
    </div>
</li>

resources/views/layouts/admin/sidebar.blade.php
<nav class="pcoded-navbar  ">
    <div class="navbar-wrapper  ">
        <div class="navbar-content scroll-div " >

            <div class="">
                <div class="main-menu-header">
                    <img class="img-radius" src="{{url('/')}}/{{Auth::user()->avatar}}" alt="User-Profile-Image">
                    <div class="user-details">
                        <span>{{ Auth::user()->name }}</span>
                       </div>
                </div>
            </div>

            <ul class="nav pcoded-inner-navbar ">


                <li class="nav-item">
                    <a href="{{route('t-shirts.index')}}" class="nav-link "><span class="pcoded-micon"><i class="fas fa-tshirt"></i></span><span class="pcoded-mtext">T-shirts</span></a>
                </li>
                <li class="nav-item">
                    <a href="{{route('t-shirts.create')}}" class="nav-link "><span class="pcoded-micon"><i class="fas fa-plus-square"></i></span><span class="pcoded-mtext">New T-shirts</span></a>
                </li>





            </ul>

        </div>
    </div>
</nav>